// <auto-generated />
using System;
using BE100.Data;
using BE100.Entities.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE100.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204134343_UpdateQuestionTypeMapping")]
    partial class UpdateQuestionTypeMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exam_result", "exam_result", new[] { "truot", "dat" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exam_status", "exam_status", new[] { "dang_do", "hoan_thanh" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_type", "question_type", new[] { "thuong", "liet" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "role", new[] { "admin", "user" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE100.Entities.Answer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_correct")
                        .HasColumnType("boolean");

                    b.Property<int>("question_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("question_id");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Role>("Role")
                        .HasColumnType("user_role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.Exam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("duration_seconds")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.ExamAnswer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("answer_id")
                        .HasColumnType("integer");

                    b.Property<int>("exam_history_id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_correct")
                        .HasColumnType("boolean");

                    b.Property<int>("question_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("answer_id");

                    b.HasIndex("exam_history_id");

                    b.HasIndex("question_id");

                    b.ToTable("ExamAnswer", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.ExamHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("current_question_id")
                        .HasColumnType("integer");

                    b.Property<int>("exam_id")
                        .HasColumnType("integer");

                    b.Property<int>("remaining_time")
                        .HasColumnType("integer");

                    b.Property<int?>("result")
                        .HasColumnType("exam_result");

                    b.Property<int>("status")
                        .HasColumnType("exam_status");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("exam_id");

                    b.HasIndex("user_id");

                    b.ToTable("ExamHistory", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.ExamQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("exam_id")
                        .HasColumnType("integer");

                    b.Property<int>("question_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("exam_id");

                    b.HasIndex("question_id");

                    b.ToTable("ExamQuestion", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<string>("question_type")
                        .IsRequired()
                        .HasColumnType("question_type");

                    b.Property<int?>("traffic_sign_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("traffic_sign_id");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.QuestionCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("QuestionCategory", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.TrafficSign", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("TrafficSign", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.TrafficSignCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("TrafficSignCategory", (string)null);
                });

            modelBuilder.Entity("BE100.Entities.Answer", b =>
                {
                    b.HasOne("BE100.Entities.Question", "question")
                        .WithMany("Answers")
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("BE100.Entities.ExamAnswer", b =>
                {
                    b.HasOne("BE100.Entities.Answer", "Answer")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("answer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE100.Entities.ExamHistory", "examHistory")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("exam_history_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE100.Entities.Question", "question")
                        .WithMany()
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("examHistory");

                    b.Navigation("question");
                });

            modelBuilder.Entity("BE100.Entities.ExamHistory", b =>
                {
                    b.HasOne("BE100.Entities.Exam", "Exam")
                        .WithMany("ExamHistories")
                        .HasForeignKey("exam_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE100.Entities.AppUser", "User")
                        .WithMany("ExamHistories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE100.Entities.ExamQuestion", b =>
                {
                    b.HasOne("BE100.Entities.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("exam_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE100.Entities.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BE100.Entities.Question", b =>
                {
                    b.HasOne("BE100.Entities.QuestionCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE100.Entities.TrafficSign", "TrafficSign")
                        .WithMany("Questions")
                        .HasForeignKey("traffic_sign_id");

                    b.Navigation("Category");

                    b.Navigation("TrafficSign");
                });

            modelBuilder.Entity("BE100.Entities.RefreshToken", b =>
                {
                    b.HasOne("BE100.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE100.Entities.TrafficSign", b =>
                {
                    b.HasOne("BE100.Entities.TrafficSignCategory", "Category")
                        .WithMany("TrafficSigns")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BE100.Entities.Answer", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("BE100.Entities.AppUser", b =>
                {
                    b.Navigation("ExamHistories");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BE100.Entities.Exam", b =>
                {
                    b.Navigation("ExamHistories");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("BE100.Entities.ExamHistory", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("BE100.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("BE100.Entities.QuestionCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BE100.Entities.TrafficSign", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BE100.Entities.TrafficSignCategory", b =>
                {
                    b.Navigation("TrafficSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
